### PR TITLE
Create deps/build.jl

### PR DESCRIPTION
**Pull request by abelsiqueira**
`Pkg.build("CUTEst")` downloads and install CUTEst on linux and osx.
Basically I created a installer for Linux, to decrease all the overhead of installing linuxbrew, but for osx I'm still using Homebrew.
Furthermore, to prevent `. $f/$f.bashrc`, I create a `cutestenv.jl` which defines the cutest variables from the installation.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Closes #50

**Comment by dpo** [comment]
I like the idea of `cutestenv.jl`. For the installation, is there no way to download and install each package, essentially as I do in the Homebrew formulas?

**Comment by abelsiqueira** [comment]
Do you mean using linuxbrew?

**Comment by dpo** [comment]
I mean using unix commands as in https://github.com/optimizers/homebrew-cutest/blob/master/sifdecode.rb#L48

**Comment by abelsiqueira** [comment]
I created the linux-cutest package for that. It's the equivalent.

**Comment by abelsiqueira** [comment]
Elaborating, I created [linux-cutest](https://github.com/abelsiqueira/linux-cutest) for the linux installation.
I tried to follow homebrew's formula for the most part.

**Pull request merged**
