### PR TITLE
Only return lower triangle of Hessian

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
This is a sneaky source of bugs for us. AMPL and JuMP models only return the lower triangle.

@abelsiqueira How should the specialized/core tests be updated? In your code-generation scripts? Could you please indicate how?

**Comment by abelsiqueira** [comment]
I think it's easier to not change `hs32.jl` nor the specialized/core tests, and change only the julia tests.

**Comment by dpo** [comment]
Done, thanks. I think the test that goes through all SIF files is too extreme.

**Comment by abelsiqueira** [comment]
This is not based on the latest develop. I changed to use only 5% of the sifs.

**Comment by dpo** [comment]
Sorry. Here we go.

**Comment by abelsiqueira** [comment]
Thank you

**Pull request merged**
